name: "Build Image"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: judy/devsecops1:latest
          push: false
          load: true

      #directory scanning
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "judy/devsecops1:latest"
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."

      #scanning software bill of material
      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
