name: "Build Image"

on:
  push:

jobs:
  scurity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: judy/devsecops1:latest
          push: false
          load: true

      # directory scanning
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "judy/devsecops1:latest"
      - name: Scan current project
        id: scan
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false

      # upload SARIF file
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      # scanning software bill of material
      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Upload SBOM
        uses: actions/upload-artifact@master
        with:
          name: sbom
          path: "${{ github.event.repository.name }}-sbom.spdx.json"
