name: "check API keys"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check API key 
        run: |
          ./check.sh
      - name: Done 
        run: |
          echo "Yaay!"