name: "Test Pipeline"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Done 
        run: |
          echo "pull_request!"
      