name: "Pull Request"

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Done
        run: |
          echo "pull_request!"
