name: "Test Pipeline"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Health 
        run: |
          yarn install
          yarn start &
          curl http://127.0.0.1:3010/hello
      - name: Done 
        run: |
          echo "Yaay!"
      

